#EXTM3U url-tvg="http://lichphatsong.xyz/schedule/epg.xml"
#PLAYLISTINF:DinhLap version="v00" url="http://bom.so/dltivi" list1="https://playlist.vthanhtivi.pw" list2="http://gg.gg/SN-90phut" /http://s.id/phimiptv

#EXTINF:0 tvg-id="dltivi" group-title="VTV" tvg-logo="https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/DltiviQR.png",Cập Nhật DLTivi
https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/CapNhatDLtivi.mp4
#EXTINF:0 tvg-id="dltivi" group-title="VTV" tvg-logo="https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/DltiviQR.png",Cập Nhật DLTivi
https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/CapNhatDLtivi.mp4
#EXTINF:0 tvg-id="dltivi" group-title="VTV" tvg-logo="https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/DltiviQR.png",Cập Nhật DLTivi
https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/CapNhatDLtivi.mp4
#EXTINF:0 tvg-id="dltivi" group-title="VTV" tvg-logo="https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/DltiviQR.png",Cập Nhật DLTivi
https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/CapNhatDLtivi.mp4