#EXTM3U url-tvg="http://lichphatsong.xyz/schedule/epg.xml"
#PLAYLISTINF:DinhLap version="v1" url="http://bom.so/dltivi" list1="https://playlist.vthanhtivi.pw" list2="http://gg.gg/SN-90phut" /http://s.id/phimiptv

#EXTINF:0 tvg-id="dltivi" group-title="VTV" tvg-logo="https://image.winudf.com/v2/image1/Y29tLmRpbmhsYXAudGl2aV9pY29uXzE2NjgzMTEzODhfMDMw/icon.webp?w=140&fakeurl=1&type=.webp",Cập Nhật DLTivi
https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/CapNhatDLtivi.mp4
#EXTINF:0 tvg-id="dltivi" group-title="VTV" tvg-logo="https://image.winudf.com/v2/image1/Y29tLmRpbmhsYXAudGl2aV9pY29uXzE2NjgzMTEzODhfMDMw/icon.webp?w=140&fakeurl=1&type=.webp",Cập Nhật DLTivi
https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/CapNhatDLtivi.mp4
#EXTINF:0 tvg-id="dltivi" group-title="VTV" tvg-logo="https://image.winudf.com/v2/image1/Y29tLmRpbmhsYXAudGl2aV9pY29uXzE2NjgzMTEzODhfMDMw/icon.webp?w=140&fakeurl=1&type=.webp",Cập Nhật DLTivi
https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/CapNhatDLtivi.mp4
#EXTINF:0 tvg-id="dltivi" group-title="VTV" tvg-logo="https://image.winudf.com/v2/image1/Y29tLmRpbmhsYXAudGl2aV9pY29uXzE2NjgzMTEzODhfMDMw/icon.webp?w=140&fakeurl=1&type=.webp",Cập Nhật DLTivi
https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/CapNhatDLtivi.mp4
#EXTINF:0 tvg-id="vtv1hd" group-title="VTV" tvg-logo="https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/VTV1_logo.png",VTV1
https://vips-livecdn.fptplay.net/hda1/vtv1hd_4000.stream/chunklist.m3u8
#EXTINF:0 tvg-id="vtv2hd" group-title="VTV" tvg-logo="https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/VTV2_logo.png",VTV2
https://livecdn.fptplay.net/hda1/vtv2_vhls.smil/chunklist_b5000000.m3u8
#EXTINF:0 tvg-id="vtv3hd" group-title="VTV" tvg-logo="https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/VTV3_logo.png",VTV3
https://livecdn.fptplay.net/hda1/vtv3hd_vhls.smil/chunklist_b5000000.m3u8
#EXTINF:0 tvg-id="vtv4hd" group-title="VTV" tvg-logo="https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/VTV4_logo.png",VTV4
https://livecdn.fptplay.net/hda1/vtv4_vhls.smil/chunklist_b5000000.m3u8
#EXTINF:0 tvg-id="vtv5hd" group-title="VTV" tvg-logo="https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/VTV5_logo.png",VTV5
https://livecdn.fptplay.net/hda2/vtv5hd_vhls.smil/chunklist_b5000000.m3u8
#EXTINF:0 tvg-id="vtv6hd" group-title="VTV" tvg-logo="https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/VTVCanTho.png",VTV Cần Thơ
https://livecdn.fptplay.net/hda1/vtvcantho_vhls.smil/chunklist_b5000000.m3u8
#EXTINF:0 tvg-id="vtv7hd" group-title="VTV" tvg-logo="https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/VTV7_logo.png",VTV7
https://vips-livecdn.fptplay.net/hda3/vtv7hd_vhls.smil/chunklist_b5000000.m3u8
#EXTINF:0 tvg-id="vtv8hd" group-title="VTV" tvg-logo="https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/VTV8_logo.png",VTV8
https://vips-livecdn.fptplay.net/hda2/vtv8hd_vhls.smil/chunklist_b5000000.m3u8
#EXTINF:0 tvg-id="vtv9hd" group-title="VTV" tvg-logo="https://raw.githubusercontent.com/DinhLap96/ListTivi/main/ListTiVi/Logo/VTV9_logo.png",VTV9
https://vips-livecdn.fptplay.net/hda2/vtv9_vhls.smil/chunklist_b5000000.m3u8
#EXTINF:0 tvg-id="qpvnhd" group-title="VTV" tvg-logo="https://upload.wikimedia.org/wikipedia/vi/5/5d/QPVN.png",Quốc Phòng TV
https://vips-livecdn.fptplay.net/hda1/quocphongvnhd_vhls.smil/chunklist_b5000000.m3u8